to_do/config/routes.rb
Rails.application.routes.draw do
  resources :lists

end

to_do/app/models/list.rb
class List < ActiveRecord::Base
end

to_do/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

to_do/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to plist_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title, :task, :deadline, :status)
  end
end

to_do/app/helpers/application_helper.rb
module ApplicationHelper
end

to_do/app/helpers/lists_helper.rb
module ListsHelper
end

to_do/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

to_do/app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= form_for @list do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>
  
  <%= f.label :task %>
  <%= f.text_field :task %>

  <%= f.label :deadline %>
  <%= f.text_field :deadline %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.submit %>
<% end %>

to_do/app/views/lists/index.html.erb
<h1>To Do Lists </h1>
<p><%= link_to 'New List', new_list_path %></p>
<% @lists.each do |list| %>
  <h2><%= list.title %></h2>
  <!-- <h3><%= list.task %></h3>
  <h3><%= list.deadline %></h3>
  <h3><%= list.status %></h3> -->
  <%= link_to 'Show list', list_path(list) %>
  <%= link_to 'Edit list', edit_list_path(list) %>
<% end %>

to_do/app/views/lists/new.html.erb
<h1>New List</h1>
<%= form_for @list do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>
  
  <%= f.label :task %>
  <%= f.text_field :task %>

  <%= f.label :deadline %>
  <%= f.text_field :deadline %>

  <%= f.label :status %>
  <%= f.text_field :status %>

  <%= f.submit %>
<% end %>

to_do/app/views/lists/show.html.erb
<h1>To Do List</h1>
<h2><%= @list.title %></h2>
<h3><%= @list.task %></h3>
<h3><%= @list.deadline %></h3>
<h3><%= @list.status %></h3>
<%= link_to 'Back', lists_path %>
<%= link_to 'Edit list', edit_list_path(@list) %>
<%= link_to 'Destroy list', list_path(@list), method: :delete %>